/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.JobGradeController;
import dao.JobGradeDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.JobGrade;

/**
 *
 * @author hp
 */
public class OJDBC_view extends javax.swing.JFrame {

    private String header[] = {"Grade Level", "Lowest Salary", "Highest Salary"};
    public JobGradeController jgc;

    /**
     * Creates new form OJDBC_view
     */
    public OJDBC_view() {
        initComponents();
        jgc = new JobGradeController();
        jgc.bindingAll(tblJobGrade, header);
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJobGrade = new javax.swing.JTable();
        pnldetail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTingkat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGajiTerendah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGajiTertinggi = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        cmbKategori = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Grade");

        tblJobGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblJobGrade.setToolTipText("ini");
        tblJobGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJobGradeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJobGrade);

        pnldetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Job Grade"));

        jLabel1.setText("Tingkat");

        txtTingkat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTingkatKeyPressed(evt);
            }
        });

        jLabel2.setText("Gaji Terendah");

        jLabel3.setText("Gaji Tertinggi");

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnldetailLayout = new javax.swing.GroupLayout(pnldetail);
        pnldetail.setLayout(pnldetailLayout);
        pnldetailLayout.setHorizontalGroup(
            pnldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGajiTerendah)
                    .addComponent(txtGajiTertinggi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        pnldetailLayout.setVerticalGroup(
            pnldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGajiTerendah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnldetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGajiTertinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade Level", "Lowest Salary", "Highest Salary" }));
        cmbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKategoriActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnldetail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnldetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String kolom = "";
        switch (cmbKategori.getSelectedIndex()) {
            case 0:
                kolom = "grade_level";
                break;
            case 1:
                kolom = "lowest_level_sal";
                break;
            case 2:
                kolom = "highest_sal";
                break;
            default:
                throw new AssertionError();
        }
        jgc.bindingSearch(tblJobGrade, header, kolom, txtSearch.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void cmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKategoriActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus data ini?");
        System.out.println(i);
        if (i==0) {
            String pesan = "Gagal Hapus";
            boolean hasil = jgc.delete(txtTingkat.getText());
            if(hasil) pesan = "Berhasil Hapus";
            JOptionPane.showMessageDialog(this, pesan);
            jgc.bindingAll(tblJobGrade, header);
            reset();
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        boolean hasil = false;
        if (!txtTingkat.isEnabled()) {
            hasil = jgc.update(txtTingkat.getText(),
                    Integer.parseInt(txtGajiTerendah.getText()),
                    Integer.parseInt(txtGajiTertinggi.getText()));
                    jgc.bindingAll(tblJobGrade, header);
        }else{
            
        hasil = jgc.insert(txtTingkat.getText(),
                Integer.parseInt(txtGajiTerendah.getText()),
                Integer.parseInt(txtGajiTertinggi.getText()));
                jgc.bindingAll(tblJobGrade, header);
        
        }

        String pesan = "Gagal Menyimpan Data";
        if (hasil) {
            pesan = "Berhasil Menyimpan Data";
        }
        JOptionPane.showMessageDialog(this, pesan);
        reset();
               
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtTingkatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTingkatKeyPressed
        // TODO add your handling code here:
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(true);
    }//GEN-LAST:event_txtTingkatKeyPressed

    private void tblJobGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJobGradeMouseClicked
        txtTingkat.setText(tblJobGrade.getValueAt(tblJobGrade.getSelectedRow(), 0) + "");
        txtGajiTerendah.setText(tblJobGrade.getValueAt(tblJobGrade.getSelectedRow(), 1) + "");
        txtGajiTertinggi.setText(tblJobGrade.getValueAt(tblJobGrade.getSelectedRow(), 2) + "");
        txtTingkat.setEnabled(false);
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(true);
    }//GEN-LAST:event_tblJobGradeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OJDBC_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OJDBC_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OJDBC_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OJDBC_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OJDBC_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnldetail;
    private javax.swing.JTable tblJobGrade;
    private javax.swing.JTextField txtGajiTerendah;
    private javax.swing.JTextField txtGajiTertinggi;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTingkat;
    // End of variables declaration//GEN-END:variables

    public void reset() {
        txtTingkat.setText("");
        txtGajiTerendah.setText("");
        txtGajiTertinggi.setText("");
        txtSearch.setText("");
        btnsimpan.setEnabled(false);
        btnhapus.setEnabled(false);
        txtTingkat.setEnabled(true);
    }
}
